### PR TITLE
DEVO-500: Update CircleCI image.

### PR DESCRIPTION
**Pull request by dkinzer**

### CODE REVIEW

**Review by sensei100 — CHANGES_REQUESTED** [review]
@dkinzer I think the Pipfile.lock should be updated since we made changes to the Pipfile.

Also, it works to just have run: pipenv install --dev.  It's a little cleaner to get rind of the command and the extra line since it isn't needed.

**Comment by dkinzer** [comment]
@sensei100 but it's running pip install on the ci without breaking.  So it should be fine.

But if you need that, would you mind just running that on your env and pushing up to this branch ... my local python setup is broken.

**Comment by sensei100** [comment]
@dkinzer Can we update the pipenv install command to be a one liner?

**Comment by sensei100** [comment]
@dkinzer Why did you close this?

**Comment by dkinzer** [comment]
@sensei100 my local python environment is busted and I don't have time to fix it today. Closing this and putting issue back to Todo

**Pull request closed without merging**
